---
title: 'PUBH 7485 Homework 2'
output: 
  github_document:
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(tableone)
library(labelled)
library(rms)
library(boot)
library(survey)
library(stats)
library(reshape2)
library(forestplot)

options(scipen = 999)
options(digits = 3)
```

```{r warning = FALSE, message = FALSE}
# Read in data
load(here("data", "OPT_Study_PUBH7485_8485_2022.Rdata"))
```

# Create Table 1
```{r warning = FALSE, message = FALSE}
# Pare down variables
opt_causal <- opt_causal %>%
  dplyr::select(
    Group, Clinic, Age, Black, White, Nat.Am, Education, Public.Asstce, BMI,
    Hypertension, Diabetes, BL.Cig.Day, BL.Drks.Day, N.prev.preg,
    Any.live.ptb.sb.sp.ab.in.ab, N.qualifying.teeth, BL.GE, BL..BOP,
    BL.PD.avg, BL.CAL.avg, BL.Calc.I, BL.Pl.I, Preg.ended...37.wk,
    Birthweight, Preg.ended
  )

# Vector of variables to summarize
myVars <- c(
  "Clinic", "Age", "Black", "White", "Nat.Am",
  "Asian", "Hisp", "Education", "Public.Asstce", "Hypertension",
  "Diabetes", "BL.Diab.Type", "BMI", "Use.Tob", "BL.Cig.Day", "Use.Alc",
  "BL.Drks.Day", "Drug.Add", "Prev.preg", "N.prev.preg", "Live.PTB",
  "Any.stillbirth", "Spont.ab", "Induced.ab", "Any.live.ptb.sb.sp.ab.in.ab",
  "N.living.kids", "N.qualifying.teeth", "BL.GE", "BL..BOP", "BL.PD.avg",
  "BL..PD.4", "BL..PD.5", "BL.CAL.avg", "BL..CAL.2", "BL..CAL.3",
  "BL.Calc.I", "BL.Pl.I", "Preg.ended...37.wk", "Birthweight"
)

# Vector of categorical variables that need transformation
catVars <- c(
  "Clinic", "Group", "Black", "White", "Nat.Am",
  "Asian", "Hisp", "Education", "Public.Asstce", "Hypertension",
  "Diabetes", "BL.Diab.Type", "Use.Tob", "Use.Alc", "Drug.Add", "Prev.preg", "Live.PTB",
  "Any.stillbirth", "Spont.ab", "Induced.ab", "Any.live.ptb.sb.sp.ab.in.ab",
  "Preg.ended...37.wk"
)

# Change variable labels
opt_causal <- set_variable_labels(opt_causal,
  Clinic = "Clinic location",
  Age = "Age (y)",
  Black = "Race: Black",
  White = "Race: White",
  Nat.Am = "Race: Native American",
  Education = "Level of Education",
  Public.Asstce = "Received public assistance for delivery",
  Hypertension = "Chronic hypertension at baseline",
  Diabetes = "Diabetes at baseline",
  BMI = "Body mass index",
  BL.Cig.Day = "# cigarettes per day",
  BL.Drks.Day = "# drinks per day",
  N.prev.preg = "# previous pregnancies",
  Any.live.ptb.sb.sp.ab.in.ab = "Previous live pre-term birth, stillbirth,
or spontaneous/induced abortion",
  N.qualifying.teeth = "# of qualifying teeth",
  BL.GE = "Whole-mouth average gingival index",
  BL..BOP = "Fraction of sites bleeding
on probing",
  BL.PD.avg = "Whole-mouth average pocket depth",
  BL.CAL.avg = "Whole-mouth average clinical attachment level",
  BL.Calc.I = "Whole-mouth average calculus index",
  BL.Pl.I = "Whole-mouth average plaque index",
  Preg.ended...37.wk = "Pregnancy ended before 37 weeks",
  Birthweight = "Birth weight (g)"
)

# Create Unweighted Table 1
tabUnmatched <- CreateTableOne(vars = myVars, strata = "Group", data = opt_causal, factorVars = catVars, test = FALSE)

tab1Mat <- print(tabUnmatched, smd = TRUE, showAllLevels = TRUE, exact = "stage", quote = FALSE, noSpaces = TRUE, printToggle = FALSE, varLabels = TRUE)

write.csv(tab1Mat, file = "homework2_table1_unwt.csv")
```

### **Question 1: Estimate the causal treatment effect using PSS and IPW.**

```{r warning = FALSE, message = FALSE}
# Function to impute missing values in continuous variables
imp_med <- function(x) {
  ifelse(is.na(x), median(x, na.rm = TRUE), x)
}

# Functions to impute missing values in categorical variables
calc_mode <- function(x) {
  distinct_values <- unique(x)
  distinct_tabulate <- tabulate(match(x, distinct_values))
  distinct_values[which.max(distinct_tabulate)]
}

imp_cat <- function(x) {
  if_else(is.na(x), calc_mode(x), x)
}

# Create vector of continuous variables
cont_vars <- c(
  "Age", "BMI", "BL.Cig.Day", "BL.Drks.Day", "N.prev.preg",
  "BL.GE", "BL..BOP", "BL.PD.avg", "BL.CAL.avg", "BL.Calc.I", "BL.Pl.I",
  "Birthweight"
)

# Create vector of categorical variables
cat_vars <- c(
  "Clinic", "Black", "White", "Nat.Am", "Education",
  "Public.Asstce", "Hypertension", "Diabetes", "Prev.preg",
  "Any.live.ptb.sb.sp.ab.in.ab", "Preg.ended...37.wk"
)

# Impute median for continuous variables
for (i in cont_vars) {
  opt_causal[[i]] <- imp_med(opt_causal[[i]])
}

# Impute most common category for continuous variables
for (i in cat_vars) {
  opt_causal[[i]] <- imp_cat(opt_causal[[i]])
}

# Check for missing data
opt_causal %>%
  is.na() %>%
  colSums()
```

## Get propensity scores
```{r warning = FALSE, message = FALSE}
# Create propensity models
# Logistic main effects
p1 <- glm(Group ~ (Clinic + Age + Black + White + Nat.Am + Education + Public.Asstce + BMI + Hypertension + Diabetes + BL.Cig.Day + BL.Drks.Day + N.prev.preg + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + BL.GE + BL..BOP + BL.PD.avg + BL.CAL.avg + BL.Calc.I + BL.Pl.I), data = opt_causal, family = "binomial")
round(summary(p1)$coefficients, digits = 3)

# Add non-linear terms
p2 <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2)), data = opt_causal, family = binomial)
round(summary(p2)$coefficients, digits = 3)
```

## Use stepwise selection for final propensity model
```{r warning = FALSE, message = FALSE}
# Full model 1 - adding nonlinear and interaction terms
fullmodel1 <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2) + Group * White + Group * Nat.Am + Group * N.prev.preg + Group * Any.live.ptb.sb.sp.ab.in.ab), data = opt_causal, family = "binomial")

model.stepwise <- step(fullmodel1, direction = "both", scope = list(upper = ~ Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2) + Group * White + Group * Nat.Am + Group * N.prev.preg + Group * Any.live.ptb.sb.sp.ab.in.ab, lower = ~1))
summary(model.stepwise)

# Note: This version performs worse in regard to balancing SMD

# Try with no interaction terms, only nonlinear
fullmodel2 <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2)), data = opt_causal, family = "binomial")

model.stepwise <- step(fullmodel2, direction = "both", scope = list(upper = ~ Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2), lower = ~1))
summary(model.stepwise)

# Note: This is much better at balancing, but the SMDs are still not as low as the first two propensity score models.

p3 <- glm(Group ~ (White + Nat.Am + Diabetes + BL.Cig.Day + Any.live.ptb.sb.sp.ab.in.ab + I(BL.PD.avg^2) + I(BL.CAL.avg^2)), data = opt_causal, family = binomial)
round(summary(p3)$coefficients, digits = 3)
```


## Check weighted differences in key variables between groups
```{r warning = FALSE, message = FALSE}
# Recode group
opt_causal <- opt_causal %>%
  mutate(group_num = fct_recode(Group,
    "1" = "T",
    "0" = "C"
  )) %>%
  mutate(group_num = as.numeric(as.character(group_num)))

# Find weighted differences: Model a
ps_a <- predict(p1, type = "response")
opt_causal$weight <- opt_causal$group_num / ps_a + (1 - opt_causal$group_num) / (1 - ps_a)
opt_svy <- svydesign(ids = ~1, data = opt_causal, weights = ~weight)
tabWeighted_a <- svyCreateTableOne(vars = myVars, strata = "Group", data = opt_svy, test = FALSE)
t2 <- print(tabWeighted_a, smd = TRUE, showAllLevels = TRUE, varLabels = TRUE)
write.csv(t2, file = "homework2_table1_a.csv")


# Find weighted differences: Model b
ps_b <- predict(p2, type = "response")
opt_causal$weight <- opt_causal$group_num / ps_b + (1 - opt_causal$group_num) / (1 - ps_b)
opt_svy <- svydesign(ids = ~1, data = opt_causal, weights = ~weight)
tabWeighted_b <- svyCreateTableOne(vars = myVars, strata = "Group", data = opt_svy, test = FALSE)
t2 <- print(tabWeighted_b, smd = TRUE, showAllLevels = TRUE, varLabels = TRUE)
write.csv(t2, file = "homework2_table1_b.csv")

# Find weighted differences: Model c
ps_c <- predict(p3, type = "response")
opt_causal$weight <- opt_causal$group_num / ps_c + (1 - opt_causal$group_num) / (1 - ps_c)
opt_svy <- svydesign(ids = ~1, data = opt_causal, weights = ~weight)
tabWeighted_c <- svyCreateTableOne(vars = myVars, strata = "Group", data = opt_svy, test = FALSE)
t2 <- print(tabWeighted_c, smd = TRUE, showAllLevels = TRUE, varLabels = TRUE)
write.csv(t2, file = "homework2_table1_c.csv")
```

## Plot of SMD

```{r warning = FALSE, message = FALSE}
dataPlot <- data.frame(
  variable = rownames(ExtractSmd(tabUnmatched)),
  Unweighted = as.numeric(ExtractSmd(tabUnmatched)),
  Weighted_logit_model_a = as.numeric(ExtractSmd(tabWeighted_a)),
  Weighted_logit_model_b = as.numeric(ExtractSmd(tabWeighted_b)),
  Weighted_logit_model_c = as.numeric(ExtractSmd(tabWeighted_c))
)
dataPlot <- dplyr::filter(
  dataPlot,
  variable != "Preg.ended" &
    variable != "Preg.ended...37.wk" &
    variable != "Birthweight"
)

## Create long-format data for ggplot2
dataPlotMelt <- melt(
  data = dataPlot,
  id.vars = c("variable"),
  variable.name = "Method",
  value.name = "SMD"
)

## Order variable names by magnitude of SMD
varNames <- as.character(dataPlot$variable)[order(dataPlot$Unweighted)]

## Order factor levels in the same order
dataPlotMelt$variable <- factor(dataPlotMelt$variable,
  levels = varNames
)

## Plot using ggplot2
ggplot(
  data = dataPlotMelt,
  mapping = aes(x = variable, y = SMD, group = Method, color = Method)
) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.1, color = "black", size = 0.1) +
  coord_flip() +
  labs(title = "Figure 1. Standardized mean difference of propensity score models, \ncompared to unweighted standardized mean difference\n") +
  theme_minimal() +
  theme(
    legend.key = element_blank(),
    plot.title = element_text(size = 12, hjust = 0.5)
  )
```


## Propensity Scores Stratification: Preterm
```{r warning = FALSE, message = FALSE}
# Preterm: Model a
ps <- predict(p1, type = "response")
ps_quintile <- cut(ps,
  breaks = c(0, quantile(ps, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
)
table(ps_quintile, opt_causal$Group)

n <- nrow(opt_causal)
nj <- table(ps_quintile)
te_quintile <- tapply(opt_causal$Preg.ended[opt_causal$Group == "T"], ps_quintile[opt_causal$Group == "T"], mean) -
  tapply(opt_causal$Preg.ended[opt_causal$Group == "C"], ps_quintile[opt_causal$Group == "C"], mean)
print(round(te_quintile, 3))
ATE_PSS <- sum(te_quintile * nj / n)
print(round(ATE_PSS, 3))

# Note: the outcome needs to be coded numerically

set.seed(2123)
B <- 100
ATE_PSS.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + Black + White + Nat.Am + Education + Public.Asstce + BMI + Hypertension + Diabetes + BL.Cig.Day + BL.Drks.Day + N.prev.preg + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + BL.GE + BL..BOP + BL.PD.avg + BL.CAL.avg + BL.Calc.I + BL.Pl.I),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  ps_quintile.boot <- cut(ps.boot,
    breaks = c(0, quantile(ps.boot, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
  )
  nj.boot <- table(ps_quintile.boot)
  te_quintile.boot <- tapply(opt.boot$Preg.ended[opt.boot$Group == "T"], ps_quintile[opt.boot$Group == "T"], mean) -
    tapply(opt.boot$Preg.ended[opt.boot$Group == "C"], ps_quintile[opt.boot$Group == "C"], mean)
  ATE.boot <- sum(te_quintile.boot * nj / n)
  ATE_PSS.boot <- c(ATE_PSS.boot, ATE.boot)
}

# Function to print results
get_results <- function() {
  print("Average Treatment Effect")
  print(ATE_PSS, digits = 3)
  SE_PSS <- sd(ATE_PSS.boot)
  print("Bootstrap SE")
  print(SE_PSS, digits = 3)
  print("Bootstrap Normal 95% CI")
  print(ATE_PSS + c(-1, 1) * qnorm(0.975) * SE_PSS, digits = 3)
  CI_PSS <- ATE_PSS + c(-1, 1) * qnorm(0.975) * SE_PSS
}

get_results()
```

```{r warning = FALSE, message = FALSE}
# Preterm: Model b
ps <- predict(p2, type = "response")
ps_quintile <- cut(ps,
  breaks = c(0, quantile(ps, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
)
table(ps_quintile, opt_causal$Group)

n <- nrow(opt_causal)
nj <- table(ps_quintile)
te_quintile <- tapply(opt_causal$Preg.ended[opt_causal$Group == "T"], ps_quintile[opt_causal$Group == "T"], mean) -
  tapply(opt_causal$Preg.ended[opt_causal$Group == "C"], ps_quintile[opt_causal$Group == "C"], mean)
print(round(te_quintile, 3))
ATE_PSS <- sum(te_quintile * nj / n)
print(round(ATE_PSS, 3))

set.seed(2123)
B <- 100
ATE_PSS.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  ps_quintile.boot <- cut(ps.boot,
    breaks = c(0, quantile(ps.boot, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
  )
  nj.boot <- table(ps_quintile.boot)
  te_quintile.boot <- tapply(opt.boot$Preg.ended[opt.boot$Group == "T"], ps_quintile[opt.boot$Group == "T"], mean) -
    tapply(opt.boot$Preg.ended[opt.boot$Group == "C"], ps_quintile[opt.boot$Group == "C"], mean)
  ATE.boot <- sum(te_quintile.boot * nj / n)
  ATE_PSS.boot <- c(ATE_PSS.boot, ATE.boot)
}

get_results()
```

```{r warning = FALSE, message = FALSE}
# Preterm: Model c
ps <- predict(p3, type = "response")
ps_quintile <- cut(ps,
  breaks = c(0, quantile(ps, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
)
table(ps_quintile, opt_causal$Group)

n <- nrow(opt_causal)
nj <- table(ps_quintile)
te_quintile <- tapply(opt_causal$Preg.ended[opt_causal$Group == "T"], ps_quintile[opt_causal$Group == "T"], mean) -
  tapply(opt_causal$Preg.ended[opt_causal$Group == "C"], ps_quintile[opt_causal$Group == "C"], mean)
print(round(te_quintile, 3))
ATE_PSS <- sum(te_quintile * nj / n)
print(round(ATE_PSS, 3))

set.seed(2123)
B <- 100
ATE_PSS.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (White + Nat.Am + Diabetes + BL.Cig.Day + Any.live.ptb.sb.sp.ab.in.ab + I(BL.PD.avg^2) + I(BL.CAL.avg^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  ps_quintile.boot <- cut(ps.boot,
    breaks = c(0, quantile(ps.boot, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
  )
  nj.boot <- table(ps_quintile.boot)
  te_quintile.boot <- tapply(opt.boot$Preg.ended[opt.boot$Group == "T"], ps_quintile[opt.boot$Group == "T"], mean) -
    tapply(opt.boot$Preg.ended[opt.boot$Group == "C"], ps_quintile[opt.boot$Group == "C"], mean)
  ATE.boot <- sum(te_quintile.boot * nj / n)
  ATE_PSS.boot <- c(ATE_PSS.boot, ATE.boot)
}

get_results()
```

## IPW: Preterm

```{r warning = FALSE, message = FALSE}
# Preterm model a
# Form Inverse Probability Weights
ps <- predict(p1, type = "response")
w1 <- opt_causal$group_num / ps
w0 <- (1 - opt_causal$group_num) / (1 - ps)

# Histogram of Standardized Weights
P.A <- prop.table(table(opt_causal$group_num))[2]
hist(w1[opt_causal$group_num == 1] / (1 / P.A), main = "Std. Weights for Treated")

# IPW2 Adjustment
ATE_IPW2 <- weighted.mean(opt_causal$Preg.ended, w1) -
  weighted.mean(opt_causal$Preg.ended, w0)
print(ATE_IPW2, digits = 3)

# Bootstrap for IPW Estimators
set.seed(2123)
B <- 100
ATE_IPW.boot <- NULL
ATE_IPW2.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + Black + White + Nat.Am + Education + Public.Asstce + BMI + Hypertension + Diabetes + BL.Cig.Day + BL.Drks.Day + N.prev.preg + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + BL.GE + BL..BOP + BL.PD.avg + BL.CAL.avg + BL.Calc.I + BL.Pl.I),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  w1.boot <- opt.boot$group_num / ps.boot
  w0.boot <- (1 - opt.boot$group_num) / (1 - ps.boot)
  ATE_IPW.boot <- c(
    ATE_IPW.boot,
    mean(opt.boot$Preg.ended * w1.boot) - mean(opt.boot$Preg.ended * w0.boot)
  )
  ATE_IPW2.boot <- c(
    ATE_IPW2.boot,
    weighted.mean(opt.boot$Preg.ended, w1.boot) - weighted.mean(opt.boot$Preg.ended, w0.boot)
  )
}

# Note: grouping variable should be numeric 0/1

# Function to get results
get_results_ipw <- function() {
  print("Average Treatment Effect")
  print(ATE_IPW2, digits = 3)
  SE_IPW2 <- sd(ATE_IPW2.boot)
  print("Bootstrap SE")
  print(SE_IPW2, digits = 3)
  print("Bootstrap Normal 95% CI")
  print(ATE_IPW2 + c(-1, 1) * qnorm(0.975) * SE_IPW2, digits = 3)
  CI_IPW2 <- ATE_IPW2 + c(-1, 1) * qnorm(0.975) * SE_IPW2
}

get_results_ipw()
```

```{r warning = FALSE, message = FALSE}
# Preterm model b
# Form Inverse Probability Weights
ps <- predict(p2, type = "response")
w1 <- opt_causal$group_num / ps
w0 <- (1 - opt_causal$group_num) / (1 - ps)

# Histogram of Standardized Weights
P.A <- prop.table(table(opt_causal$group_num))[2]
hist(w1[opt_causal$group_num == 1] / (1 / P.A), main = "Std. Weights for Treated")

# IPW2 Adjustment
ATE_IPW2 <- weighted.mean(opt_causal$Preg.ended, w1) -
  weighted.mean(opt_causal$Preg.ended, w0)
print(ATE_IPW2, digits = 3)

# Bootstrap for IPW Estimators
set.seed(2123)
B <- 100
ATE_IPW.boot <- NULL
ATE_IPW2.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  w1.boot <- opt.boot$group_num / ps.boot
  w0.boot <- (1 - opt.boot$group_num) / (1 - ps.boot)
  ATE_IPW.boot <- c(
    ATE_IPW.boot,
    mean(opt.boot$Preg.ended * w1.boot) - mean(opt.boot$Preg.ended * w0.boot)
  )
  ATE_IPW2.boot <- c(
    ATE_IPW2.boot,
    weighted.mean(opt.boot$Preg.ended, w1.boot) - weighted.mean(opt.boot$Preg.ended, w0.boot)
  )
}

get_results_ipw()
```

```{r warning = FALSE, message = FALSE}
# Preterm model c
# Form Inverse Probability Weights
ps <- predict(p3, type = "response")
w1 <- opt_causal$group_num / ps
w0 <- (1 - opt_causal$group_num) / (1 - ps)

# Histogram of Standardized Weights
P.A <- prop.table(table(opt_causal$group_num))[2]
hist(w1[opt_causal$group_num == 1] / (1 / P.A), main = "Std. Weights for Treated")

# IPW2 Adjustment
ATE_IPW2 <- weighted.mean(opt_causal$Preg.ended, w1) -
  weighted.mean(opt_causal$Preg.ended, w0)
print(ATE_IPW2, digits = 3)

# Bootstrap for IPW Estimators
set.seed(2123)
B <- 100
ATE_IPW.boot <- NULL
ATE_IPW2.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (White + Nat.Am + Diabetes + BL.Cig.Day + Any.live.ptb.sb.sp.ab.in.ab + I(BL.PD.avg^2) + I(BL.CAL.avg^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  w1.boot <- opt.boot$group_num / ps.boot
  w0.boot <- (1 - opt.boot$group_num) / (1 - ps.boot)
  ATE_IPW.boot <- c(
    ATE_IPW.boot,
    mean(opt.boot$Preg.ended * w1.boot) - mean(opt.boot$Preg.ended * w0.boot)
  )
  ATE_IPW2.boot <- c(
    ATE_IPW2.boot,
    weighted.mean(opt.boot$Preg.ended, w1.boot) - weighted.mean(opt.boot$Preg.ended, w0.boot)
  )
}

get_results_ipw()
```


## PSS: Birth weight
```{r warning = FALSE, message = FALSE}
# BW: Model a
ps <- predict(p1, type = "response")
ps_quintile <- cut(ps,
  breaks = c(0, quantile(ps, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
)
table(ps_quintile, opt_causal$Group)

n <- nrow(opt_causal)
nj <- table(ps_quintile)
te_quintile <- tapply(opt_causal$Birthweight[opt_causal$Group == "T"], ps_quintile[opt_causal$Group == "T"], mean) -
  tapply(opt_causal$Birthweight[opt_causal$Group == "C"], ps_quintile[opt_causal$Group == "C"], mean)
print(round(te_quintile, 3))
ATE_PSS <- sum(te_quintile * nj / n)
print(round(ATE_PSS, 3))

# Note: the outcome needs to be coded numerically

set.seed(2123)
B <- 100
ATE_PSS.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + Black + White + Nat.Am + Education + Public.Asstce + BMI + Hypertension + Diabetes + BL.Cig.Day + BL.Drks.Day + N.prev.preg + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + BL.GE + BL..BOP + BL.PD.avg + BL.CAL.avg + BL.Calc.I + BL.Pl.I),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  ps_quintile.boot <- cut(ps.boot,
    breaks = c(0, quantile(ps.boot, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
  )
  nj.boot <- table(ps_quintile.boot)
  te_quintile.boot <- tapply(opt.boot$Birthweight[opt.boot$Group == "T"], ps_quintile[opt.boot$Group == "T"], mean) -
    tapply(opt.boot$Birthweight[opt.boot$Group == "C"], ps_quintile[opt.boot$Group == "C"], mean)
  ATE.boot <- sum(te_quintile.boot * nj / n)
  ATE_PSS.boot <- c(ATE_PSS.boot, ATE.boot)
}

get_results()
```

```{r warning = FALSE, message = FALSE}
# BW: Model b
ps <- predict(p2, type = "response")
ps_quintile <- cut(ps,
  breaks = c(0, quantile(ps, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
)
table(ps_quintile, opt_causal$Group)

n <- nrow(opt_causal)
nj <- table(ps_quintile)
te_quintile <- tapply(opt_causal$Birthweight[opt_causal$Group == "T"], ps_quintile[opt_causal$Group == "T"], mean) -
  tapply(opt_causal$Birthweight[opt_causal$Group == "C"], ps_quintile[opt_causal$Group == "C"], mean)
print(round(te_quintile, 3))
ATE_PSS <- sum(te_quintile * nj / n)
print(round(ATE_PSS, 3))

set.seed(2123)
B <- 100
ATE_PSS.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  ps_quintile.boot <- cut(ps.boot,
    breaks = c(0, quantile(ps.boot, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
  )
  nj.boot <- table(ps_quintile.boot)
  te_quintile.boot <- tapply(opt.boot$Birthweight[opt.boot$Group == "T"], ps_quintile[opt.boot$Group == "T"], mean) -
    tapply(opt.boot$Birthweight[opt.boot$Group == "C"], ps_quintile[opt.boot$Group == "C"], mean)
  ATE.boot <- sum(te_quintile.boot * nj / n)
  ATE_PSS.boot <- c(ATE_PSS.boot, ATE.boot)
}

get_results()
```

```{r warning = FALSE, message = FALSE}
# BW: Model c
ps <- predict(p3, type = "response")
ps_quintile <- cut(ps,
  breaks = c(0, quantile(ps, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
)
table(ps_quintile, opt_causal$Group)

n <- nrow(opt_causal)
nj <- table(ps_quintile)
te_quintile <- tapply(opt_causal$Birthweight[opt_causal$Group == "T"], ps_quintile[opt_causal$Group == "T"], mean) -
  tapply(opt_causal$Birthweight[opt_causal$Group == "C"], ps_quintile[opt_causal$Group == "C"], mean)
print(round(te_quintile, 3))
ATE_PSS <- sum(te_quintile * nj / n)
print(round(ATE_PSS, 3))

set.seed(2123)
B <- 100
ATE_PSS.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (White + Nat.Am + Diabetes + BL.Cig.Day + Any.live.ptb.sb.sp.ab.in.ab + I(BL.PD.avg^2) + I(BL.CAL.avg^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  ps_quintile.boot <- cut(ps.boot,
    breaks = c(0, quantile(ps.boot, p = c(0.2, 0.4, 0.6, 0.8)), 1), labels = 1:5
  )
  nj.boot <- table(ps_quintile.boot)
  te_quintile.boot <- tapply(opt.boot$Birthweight[opt.boot$Group == "T"], ps_quintile[opt.boot$Group == "T"], mean) -
    tapply(opt.boot$Birthweight[opt.boot$Group == "C"], ps_quintile[opt.boot$Group == "C"], mean)
  ATE.boot <- sum(te_quintile.boot * nj / n)
  ATE_PSS.boot <- c(ATE_PSS.boot, ATE.boot)
}

get_results()
```

## IPW: Birth weight

```{r warning = FALSE, message = FALSE}
# BW model a
# Form Inverse Probability Weights
ps <- predict(p1, type = "response")
w1 <- opt_causal$group_num / ps
w0 <- (1 - opt_causal$group_num) / (1 - ps)

# Histogram of Standardized Weights
P.A <- prop.table(table(opt_causal$group_num))[2]
hist(w1[opt_causal$group_num == 1] / (1 / P.A), main = "Std. Weights for Treated")

# IPW2 Adjustment
ATE_IPW2 <- weighted.mean(opt_causal$Birthweight, w1) -
  weighted.mean(opt_causal$Birthweight, w0)
print(ATE_IPW2, digits = 3)

# Bootstrap for IPW Estimators
set.seed(2123)
B <- 100
ATE_IPW.boot <- NULL
ATE_IPW2.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + Black + White + Nat.Am + Education + Public.Asstce + BMI + Hypertension + Diabetes + BL.Cig.Day + BL.Drks.Day + N.prev.preg + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + BL.GE + BL..BOP + BL.PD.avg + BL.CAL.avg + BL.Calc.I + BL.Pl.I),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  w1.boot <- opt.boot$group_num / ps.boot
  w0.boot <- (1 - opt.boot$group_num) / (1 - ps.boot)
  ATE_IPW.boot <- c(
    ATE_IPW.boot,
    mean(opt.boot$Birthweight * w1.boot) - mean(opt.boot$Birthweight * w0.boot)
  )
  ATE_IPW2.boot <- c(
    ATE_IPW2.boot,
    weighted.mean(opt.boot$Birthweight, w1.boot) - weighted.mean(opt.boot$Birthweight, w0.boot)
  )
}

# Note: grouping variable should be numeric 0/1

get_results_ipw()
```

```{r warning = FALSE, message = FALSE}
# BW model b
# Form Inverse Probability Weights
ps <- predict(p2, type = "response")
w1 <- opt_causal$group_num / ps
w0 <- (1 - opt_causal$group_num) / (1 - ps)

# Histogram of Standardized Weights
P.A <- prop.table(table(opt_causal$group_num))[2]
hist(w1[opt_causal$group_num == 1] / (1 / P.A), main = "Std. Weights for Treated")

# IPW2 Adjustment
ATE_IPW2 <- weighted.mean(opt_causal$Birthweight, w1) -
  weighted.mean(opt_causal$Birthweight, w0)
print(ATE_IPW2, digits = 3)

# Bootstrap for IPW Estimators
set.seed(2123)
B <- 100
ATE_IPW.boot <- NULL
ATE_IPW2.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (Clinic + Age + I(Age^2) + Black + White + Nat.Am + Education + Public.Asstce + BMI + I(BMI^2) + Hypertension + Diabetes + BL.Cig.Day + I(BL.Cig.Day^2) + BL.Drks.Day + I(BL.Drks.Day^2) + N.prev.preg + I(N.prev.preg^2) + Any.live.ptb.sb.sp.ab.in.ab + N.qualifying.teeth + I(N.qualifying.teeth^2) + BL.GE + I(BL.GE^2) + BL..BOP + I(BL..BOP^2) + BL.PD.avg + I(BL.PD.avg^2) + BL.CAL.avg + I(BL.CAL.avg^2) + BL.Calc.I + I(BL.Calc.I^2) + BL.Pl.I + I(BL.Pl.I^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  w1.boot <- opt.boot$group_num / ps.boot
  w0.boot <- (1 - opt.boot$group_num) / (1 - ps.boot)
  ATE_IPW.boot <- c(
    ATE_IPW.boot,
    mean(opt.boot$Birthweight * w1.boot) - mean(opt.boot$Birthweight * w0.boot)
  )
  ATE_IPW2.boot <- c(
    ATE_IPW2.boot,
    weighted.mean(opt.boot$Birthweight, w1.boot) - weighted.mean(opt.boot$Birthweight, w0.boot)
  )
}

get_results_ipw()
```

```{r warning = FALSE, message = FALSE}
# BW model c
# Form Inverse Probability Weights
ps <- predict(p3, type = "response")
w1 <- opt_causal$group_num / ps
w0 <- (1 - opt_causal$group_num) / (1 - ps)

# Histogram of Standardized Weights
P.A <- prop.table(table(opt_causal$group_num))[2]
hist(w1[opt_causal$group_num == 1] / (1 / P.A), main = "Std. Weights for Treated")

# IPW2 Adjustment
ATE_IPW2 <- weighted.mean(opt_causal$Birthweight, w1) -
  weighted.mean(opt_causal$Birthweight, w0)
print(ATE_IPW2, digits = 3)

# Bootstrap for IPW Estimators
set.seed(2123)
B <- 100
ATE_IPW.boot <- NULL
ATE_IPW2.boot <- NULL
n <- nrow(opt_causal)
for (i in 1:B) {
  opt.boot <- opt_causal[sample(1:n, n, replace = TRUE), ]
  p1.boot <- glm(Group ~ (White + Nat.Am + Diabetes + BL.Cig.Day + Any.live.ptb.sb.sp.ab.in.ab + I(BL.PD.avg^2) + I(BL.CAL.avg^2)),
    data = opt.boot, family = "binomial"
  )
  ps.boot <- predict(p1.boot, type = "response")
  w1.boot <- opt.boot$group_num / ps.boot
  w0.boot <- (1 - opt.boot$group_num) / (1 - ps.boot)
  ATE_IPW.boot <- c(
    ATE_IPW.boot,
    mean(opt.boot$Birthweight * w1.boot) - mean(opt.boot$Birthweight * w0.boot)
  )
  ATE_IPW2.boot <- c(
    ATE_IPW2.boot,
    weighted.mean(opt.boot$Birthweight, w1.boot) - weighted.mean(opt.boot$Birthweight, w0.boot)
  )
}

get_results_ipw()
```

# Question 2: Forest plot of estimates and 95% CIs
```{r warning = FALSE, message = FALSE}
# Read in previously created csv files
est_preterm <- read_csv(here("pubh_7485_homework2", "pubh_7485_hw_2_all_preterm.csv"))
est_bw <- read_csv(here("pubh_7485_homework2", "pubh_7485_hw_2_all_bw.csv"))

# Forest plot for preterm
forestplot(est_preterm,
  mean = ATE,
  lower = lower,
  upper = upper,
  labeltext = Method,
  col = fpColors(
    box = "lightsteelblue3",
    line = "lightsteelblue4",
    summary = "lightsteelblue3"
  ),
  title = "Figure 2. Forest plot comparing ATE and 95% CIs for \npregnancy ending before 37 weeks"
)

# Forest plot for birth weight
forestplot(est_bw,
  mean = ATE,
  lower = lower,
  upper = upper,
  labeltext = Method,
  col = fpColors(
    box = "goldenrod1",
    line = "goldenrod3",
    summary = "goldenrod1"
  ),
  title = "Figure 3. Forest plot comparing ATE and 95% CIs \nfor birth weight"
)
```
